```{r setup}
#| message: false
#| warning: false
library(terra)
library(sf)
library(docxtractr)
library(tidyverse)
library(readxl)
```

# Comparing maps {.unnumbered}

```{r}
#| message: false
#| warning: false
area <- list.files("data/umrbpl/", full.names = TRUE, pattern = "shp$") |>
  read_sf() |>
  st_transform(crs = "EPSG:4326")
```

## NGP project 

These plots are from a reforestation project (secondary forests) in Upper Marikina. The plots are xxx ha in size. 

```{r}
#| message: false
#| warning: false
# NGP project
ngp <- list.files("data/inventories/", "NGP", full.names = TRUE) |>
  read_docx() |>
  docx_extract_tbl(1) |>
  set_names(c(
    "plot",
    paste0(rep(c("agb", "agc"), 2), rep(c("_h", ""), each = 2))
  )) |>
  filter(!grepl("Average|Transect", plot)) |>
  mutate(plot = paste0(rep(c(1:23, 27), each = 3), "_", rep(1:3, 24))) |>
  mutate(across(contains("ag"), function(x) {
    ifelse(is.na(as.numeric(x)), 0, as.numeric(x))
  }))

location_ngp <-
  read_excel("data/inventories/Carbon Stock and Sequestration Data.xlsx",
    sheet = "NGP_Carbon Assessment", range = "B3:E84"
  ) |>
  set_names(c("plot", "x", "y", "elev")) |>
  mutate(transect = rep(1:27, each = 3)) |>
  mutate(plot = paste(transect, plot, sep = "_")) |>
  group_by(transect) |>
  # correct problematic x and y values
  mutate(
    x = ifelse(abs(x - median(x)) > 1e4, median(x), x),
    y = ifelse(abs(y - median(y)) > 1e4, median(y), y)
  )

df_ngp <- left_join(ngp, location_ngp) |>
  separate(plot, c("transect", "plot")) |>
  group_by(transect) |>
  summarise(agb = mean(agb_h), x = round(mean(x)), y = round(mean(y)))
sf_ngp <- df_ngp |>
  st_as_sf(coords = c("x", "y"), crs = 32651) |> # check which CRS was used!!
  st_transform(crs = "EPSG:4326")

df_ngp |>
  ggplot(aes(agb)) +
  geom_histogram() +
  labs(x = "Aboveground biomass density (Mg/ha)") +
  theme_classic()
```

## BAMS plots

```{r}
#| message: false
#| warning: false
# BAMS plots
bams <- list.files("data/inventories/", "BAMS", full.names = TRUE) |>
  read_docx() |>
  docx_extract_tbl(1) |>
  set_names(c(
    "plot",
    paste0(rep(c("agb", "agc"), 2), rep(c("_h", ""), each = 2))
  )) |>
  mutate(across(contains("ag"), as.numeric))
location_bams <-
  read_excel("data/inventories/Carbon Stock and Sequestration Data.xlsx",
    sheet = "BAMS_Data", range = "A2:C38"
  ) |>
  rename_with(tolower) |>
  mutate(plot = as.character(rep(1:9, each = 4))) |>
  separate(coordinates, c("x", "y")) |>
  mutate(across(c("x", "y"), as.numeric)) |>
  group_by(plot) |>
  summarise(x = mean(x), y = mean(y))
df_bams <- left_join(bams, location_bams) |>
  select(plot, x, y, agb_h) |>
  rename(agb = agb_h)
df_bams |>
  ggplot(aes(agb)) +
  geom_histogram() +
  labs(x = "Aboveground biomass density (Mg/ha)") +
  theme_classic()
```

## FRA plots

```{r}
#| message: false
#| warning: false
fra <- list.files("data/inventories/", "FRA", full.names = TRUE) |>
  read_docx() |>
  docx_extract_tbl(1) |>
  set_names(c(
    "track", "plot",
    paste0(rep(c("agb", "agc"), 2), rep(c("_h", ""), each = 2))
  )) |>
  mutate(across(1:6, as.numeric)) |>
  filter(!is.na(plot)) |>
  fill(track, .direction = "down")
## FRA plots
sf_fra <- st_read("data/inventories/Subplots_Tract105/Subplots_Tract105.shp") |>
  mutate(dataset = "fra") |>
  mutate(plot = paste0("105_", gsub("Plot ", "", PLOT)))

fra |>
  ggplot(aes(agb_h)) +
  geom_histogram() +
  geom_vline(xintercept = median(fra$agb_h), lty = 2) +
  annotate(
    geom = "text", x = median(fra$agb_h) + 50, y = 10, angle = 90,
    label = paste("Median:", round(median(fra$agb_h)))
  ) +
  geom_vline(xintercept = mean(fra$agb_h), lty = 2) +
  annotate(
    geom = "text", x = mean(fra$agb_h) + 50, y = 10, angle = 90,
    label = paste("Mean:", round(mean(fra$agb_h)))
  ) +
  labs(x = "Aboveground biomass density (Mg/ha)") +
  theme_classic()
```

## Location of the plots

```{r}
#| message: false
#| warning: false
df_fra <- fra |>
  mutate(dataset = "fra", plot = paste(track, plot, sep = "_")) |>
  select(dataset, plot, agb_h) |>
  rename(agb = agb_h)
df_all <- df_ngp |>
  rename(plot = transect) |>
  mutate(dataset = "ngp") |>
  bind_rows(mutate(df_bams, dataset = "bams")) |>
  bind_rows(df_fra) |>
  select(-x, -y)
location_ngp <- df_ngp |>
  select(transect, x, y) |>
  rename(plot = transect)
sf_all <-
  bind_rows(list(ngp = location_ngp, bams = location_bams), .id = "dataset") |>
  st_as_sf(coords = c("x", "y"), crs = 32651) |> # check which CRS was used!!
  bind_rows(sf_fra) |>
  st_transform(crs = "EPSG:4326")
ggplot() +
  geom_sf(data = area) +
  geom_sf(data = sf_all, aes(col = dataset))
```


# Comparison with biomass maps

```{r}
#| message: false
#| warning: false
diagnostic <- function(x, y) {
  rmse <- signif(sqrt(mean((x - y)^2, na.rm = TRUE)), 3)
  mape <- signif(mean(abs((x - y) / x), na.rm = TRUE) * 100, 3)
  r2 <- signif(cor(x, y, use = "complete.obs")^2, 2)
  bias <- signif(mean(x - y, na.rm = TRUE), 3)
  cat(
    "RMSE:", rmse,
    "Mg/ha\nMAPE:", mape,
    "%\nR²:", r2, "\nBias:",
    bias, "Mg/ha"
  )
}
```

```{r}
robust_extract <- function(coord, rst) {
  if (nrow(coord) > 0) {
    val <- terra::extract(rst, coord)[, 2] |> mean()
  } else {
    val <- NA
  }
}
```

## CCI maps

We match the year of the inventory to the closest year of the map.

```{r}
#| message: false
#| warning: false
cci <- list.files("data/biomass/", "AGB-MERGED", full.names = TRUE) |>
  rast()
names(cci) <- do.call(cbind, strsplit(names(cci), "-"))[7, ]

# check inventory year
df_all$year <- 2010
df_all$cci_carbon <- sapply(seq_len(nrow(df_all)), function(i) {
  closest <- which.min(abs(as.numeric(names(cci)) - df_all$year[i]))
  sf_all |>
    filter(dataset == df_all$dataset[i] & plot == df_all$plot[i]) |>
    robust_extract(cci[[closest]])
})
diagnostic(df_all$agb, df_all$cci_carbon)
```

## Global forest watch map

```{r}
#| message: false
#| warning: false
gfw <- list.files("data/biomass/", "harris", full.names = TRUE) |>
  rast()
df_all$gfw_carbon <- sapply(seq_len(nrow(df_all)), function(i) {
  sf_all |>
    filter(dataset == df_all$dataset[i] & plot == df_all$plot[i]) |>
    robust_extract(gfw)
})
diagnostic(df_all$agb, df_all$gfw_carbon)
```

## ORNL map

```{r}
#| message: false
#| warning: false
ornl <- list.files("data/biomass/", "aboveground", full.names = TRUE) |>
  rast()
df_all$ornl_carbon <- sapply(seq_len(nrow(df_all)), function(i) {
  sf_all |>
    filter(dataset == df_all$dataset[i] & plot == df_all$plot[i]) |>
    robust_extract(ornl)
})
diagnostic(df_all$agb, df_all$ornl_carbon)
```

## Map choice

```{r}
#| message: false
#| warning: false
#| fig-width: 10
#| fig-height: 4
df_all |>
  pivot_longer(cols = contains("_carbon")) |>
  filter(!is.na(value)) |>
  mutate(name = gsub("_carbon", "", name)) |>
  ggplot(aes(agb, value, col = dataset)) +
  geom_point() +
  facet_wrap(~name, scale = "free") +
  labs(x = "Ground-based AGB (Mg/ha)", y = "Remote-sensing AGB (Mg/ha)") +
  geom_abline(slope = 1, intercept = 0, lty = 2)
```

The final map chosen is ...
